#index:
#    path: /
#    controller: App\Controller\DefaultController::index

todolist_index:
  path:     /
  defaults: { _controller: App\Controller\DefaultController::index }

security_login:
  path:     /login
  defaults: { _controller: App\Controller\SecurityController::login }


security_logout:
  path:     /logout
  defaults: { _controller: App\Controller\SecurityController::logout }


todolist_createuser:
  path:     /userarea/createuser
  defaults: { _controller: App\Controller\UserController::createUser }




todolist_edituser:
  path:     /userarea/edituser/{id}
  defaults: { _controller: App\Controller\UserController::editUser }



todolist_listuser:
  path:     /userarea/listuser
  defaults: { _controller: App\Controller\UserController::listUser }




todolist_createtask:
  path:     /createtask
  defaults: { _controller: App\Controller\TaskController::createTask }



todolist_listtask:
  path:     /listtask
  defaults: { _controller: App\Controller\TaskController::listTask }



todolist_listtaskdone:
  path:     /listtaskdone
  defaults: { _controller: App\Controller\TaskController::listTaskdone }





todolist_listtaskisnotdone:
  path:     /listtaskisnotdone
  defaults: { _controller: App\Controller\TaskController::listTaskisnotdone }


todolist_edittask:
  path:     /edittask/{id}
  defaults: { _controller: App\Controller\TaskController::editTask }


todolist_toggletask:
  path:     /toggletask/{id}
  defaults: { _controller: App\Controller\TaskController::toggleTask }

todolist_deletetask:
  path:     /deletetask/{id}
  defaults: { _controller: App\Controller\TaskController::deleteTask }