#index:
#    path: /
#    controller: App\Controller\DefaultController::index

todolist_index:
  path:     /
  defaults: { _controller: App\Controller\DefaultController::index }

security_login:
  path:     /login
  defaults: { _controller: App\Controller\SecurityController::login }


security_logout:
  path:     /logout
  defaults: { _controller: App\Controller\SecurityController::logout }


todolist_usercreate:
  path:     /usercreate
  defaults: { _controller: App\Controller\UserController::usercreate }




todolist_useredit:
  path:     /useredit
  defaults: { _controller: App\Controller\UserController::useredit }



todolist_userlist:
  path:     /userlist
  defaults: { _controller: App\Controller\UserController::userlist }




todolist_taskcreate:
  path:     /taskcreate
  defaults: { _controller: App\Controller\TaskController::taskcreate }



todolist_tasklist:
  path:     /tasklist
  defaults: { _controller: App\Controller\TaskController::tasklist }