#index:
#    path: /
#    controller: App\Controller\DefaultController::index

todolist_index:
  path:     /
  defaults: { _controller: App\Controller\DefaultController::index }

security_login:
  path:     /login
  defaults: { _controller: App\Controller\SecurityController::login }


security_logout:
  path:     /logout
  defaults: { _controller: App\Controller\SecurityController::logout }


todolist_createuser:
  path:     /createuser
  defaults: { _controller: App\Controller\UserController::createUser }




todolist_edituser:
  path:     /edituser
  defaults: { _controller: App\Controller\UserController::editUser }



todolist_listuser:
  path:     /listuser
  defaults: { _controller: App\Controller\UserController::listUser }




todolist_createtask:
  path:     /createtask
  defaults: { _controller: App\Controller\TaskController::createTask }



todolist_listtask:
  path:     /listtask
  defaults: { _controller: App\Controller\TaskController::listTask }



todolist_edittask:
  path:     /edittask
  defaults: { _controller: App\Controller\TaskController::editTask }


todolist_toggletask:
  path:     /toggletask/{id}
  defaults: { _controller: App\Controller\TaskController::toggleTask }

todolist_deletetask:
  path:     /deletetask
  defaults: { _controller: App\Controller\TaskController::deleteTask }